---
title: "Carbon Emissions Graph"
author: "Tsz Yau Iris Chow"
date: "3/10/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
library("dplyr")
library("tidyr")
library(tidyverse)
```

```{r}
carbon <- read.csv("carbon-monitor-US.csv")
```

```{r echo=TRUE}

#remove rows with NA
carbon <- na.omit(carbon)

#remove country column
carbon$country...group.of.countries = NULL

head(carbon)

#modify dates
carbon <- carbon %>%
  mutate(date = as.Date(date, format = "%d/%m/%Y")) 
```

### Creating graphs

```{r}
library("ggplot2")
library("dplyr")
library("dslabs")
library("readr")
library("zoo")
theme_set(theme_bw())
```

```{r }
carbon$roll7 = rollmean(carbon$MtCO2.per.day, 10, na.pad=TRUE)
carbon <- carbon %>%
  na.omit()
plot <- ggplot(carbon, aes(x = date, y = MtCO2.per.day)) +
  geom_line()+
  ggtitle("Carbon Emissions in the US by Sector")+
  labs(x = "Date",y = "Carbon Emissions (Mt)", caption = "Red line indicates date of first covid outbreak in the US (Janarary 19th, 2020) \n Blue line indicates date of first stay-at-home order goes into effect (March 19th, 2020)")+
  geom_vline(xintercept =as.Date("19/01/2020","%d/%m/%Y"), color = "red", linetype = "solid")+
  geom_vline(xintercept =as.Date("19/03/2020","%d/%m/%Y"), color = "blue", linetype = "solid")  +
  facet_wrap(~sector)+
  geom_line(aes(y=roll7), col = "green")+scale_x_date(date_labels = "%b-%y")
plot
```



